/* Regenerates app/js/docs-embedded.js from the markdown files in /docs
   so the in-app Help works offline. Run with any Node.js:
     node tools/embed-docs.js                                            */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const docsDir = path.join(root, 'docs');
const outFile = path.join(root, 'app', 'js', 'docs-embedded.js');

const ORDER = [
  ['USER_GUIDE.md', 'guide', 'User Guide'],
  ['LASER_WORKFLOW.md', 'laser', 'Laser Workflow'],
  ['SHORTCUTS.md', 'shortcuts', 'Keyboard Shortcuts'],
  ['FAQ.md', 'faq', 'FAQ & Troubleshooting'],
  ['AI_ASSISTANT.md', 'assistant', 'AI Assistant (MCP)'],
  ['CUSTOMIZING.md', 'customizing', 'Customizing the App'],
];

const docs = [];
for (const [file, id, title] of ORDER) {
  const p = path.join(docsDir, file);
  if (!fs.existsSync(p)) { console.warn('missing', file); continue; }
  docs.push({ id, title, md: fs.readFileSync(p, 'utf8') });
}

const body = '/* Generated by tools/embed-docs.js — do not edit by hand. */\n' +
  'window.CF_DOCS = ' + JSON.stringify(docs, null, 0) + ';\n';
fs.writeFileSync(outFile, body);
console.log(`Wrote ${outFile} (${docs.length} docs, ${(body.length / 1024).toFixed(0)} KB)`);