# Downloads open-license (OFL) display fonts suited to coin design from Google Fonts
# and emits app/js/fonts-data.js with base64-embedded woff2 data so the app works
# fully offline from file:// or Electron with no CORS issues.
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$root = Split-Path -Parent $PSScriptRoot
$fontDir = Join-Path $root 'app\assets\fonts'
New-Item -ItemType Directory -Force $fontDir | Out-Null

$UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

# family query fragments -> [display label, category]
$families = @(
    @{ q = 'Cinzel:wght@400;700;900'; label = 'Cinzel' },
    @{ q = 'Cinzel+Decorative:wght@700'; label = 'Cinzel Decorative' },
    @{ q = 'EB+Garamond:ital,wght@0,500;1,500'; label = 'EB Garamond' },
    @{ q = 'Bebas+Neue'; label = 'Bebas Neue' },
    @{ q = 'Oswald:wght@500'; label = 'Oswald' },
    @{ q = 'Black+Ops+One'; label = 'Black Ops One' },
    @{ q = 'Great+Vibes'; label = 'Great Vibes' },
    @{ q = 'Pirata+One'; label = 'Pirata One' },
    @{ q = 'Rye'; label = 'Rye' },
    @{ q = 'Special+Elite'; label = 'Special Elite' }
)

$entries = New-Object System.Collections.ArrayList
foreach ($f in $families) {
    try {
        $cssUrl = "https://fonts.googleapis.com/css2?family=$($f.q)&display=swap"
        $css = (Invoke-WebRequest -Uri $cssUrl -Headers @{ 'User-Agent' = $UA } -UseBasicParsing).Content
        # split per @font-face block, keep latin blocks only (unicode-range containing U+0000)
        $blocks = [regex]::Matches($css, '@font-face\s*\{[^}]*\}')
        foreach ($b in $blocks) {
            $t = $b.Value
            if ($t -notmatch 'U\+0000') { continue }
            $fam = [regex]::Match($t, "font-family:\s*'([^']+)'").Groups[1].Value
            $sty = [regex]::Match($t, 'font-style:\s*(\w+)').Groups[1].Value
            $wgt = [regex]::Match($t, 'font-weight:\s*(\d+)').Groups[1].Value
            $url = [regex]::Match($t, 'url\((https[^)]+\.woff2)\)').Groups[1].Value
            if (-not $url) { continue }
            $safe = ($fam -replace '[^A-Za-z0-9]', '') + "-$wgt-$sty.woff2"
            $path = Join-Path $fontDir $safe
            Invoke-WebRequest -Uri $url -Headers @{ 'User-Agent' = $UA } -OutFile $path -UseBasicParsing
            $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($path))
            [void]$entries.Add(@{ family = $fam; weight = [int]$wgt; style = $sty; b64 = $b64 })
            Write-Host "OK  $fam $wgt $sty  ($([math]::Round((Get-Item $path).Length/1kb))kb)"
        }
    } catch {
        Write-Host "SKIP $($f.label): $($_.Exception.Message)"
    }
}

$js = New-Object System.Text.StringBuilder
[void]$js.AppendLine('// Generated by tools/get-fonts.ps1 - base64-embedded OFL fonts (Google Fonts).')
[void]$js.AppendLine('window.CF_FONTS_DATA = [')
foreach ($e in $entries) {
    [void]$js.AppendLine("{family:'$($e.family)',weight:$($e.weight),style:'$($e.style)',b64:'$($e.b64)'},")
}
[void]$js.AppendLine('];')
[IO.File]::WriteAllText((Join-Path $root 'app\js\fonts-data.js'), $js.ToString())
Write-Host "Wrote fonts-data.js with $($entries.Count) faces."